- openwebstart/src/main/java/com/openwebstart/jvm/LocalRuntimeManager.java
- openwebstart/src/main/java/com/openwebstart/jvm/io/DownloadInputStream.java
- openwebstart/src/main/java/com/openwebstart/jvm/localfinder/MacRuntimeFinder.java
- openwebstart/src/main/java/com/openwebstart/jvm/localfinder/RuntimeFinder.java
- openwebstart/src/main/java/com/openwebstart/jvm/localfinder/RuntimeFinderUtils.java
- openwebstart/src/main/java/com/openwebstart/jvm/ui/RuntimeManagerPanel.java
Util class to receive information about runtime added
> Util class to receive information about runtime added

- openwebstart/src/main/java/com/openwebstart/launcher/OwsJvmLauncher.java
this PR depends on changes in https://github.com/AdoptOpenJDK/IcedTea-Web/pull/416
> hide ITW splashscreen via environment variable setting

- openwebstart/src/main/java/com/openwebstart/launcher/OpenWebStartControlPanelStyle.java
> ITW added to header

- openwebstart/src/main/java/com/openwebstart/controlpanel/SimplifiedJvmPanel.java
- openwebstart/src/main/java/com/openwebstart/controlpanel/SimplifiedJvmPanelProvider.java
- openwebstart/src/main/java/com/openwebstart/jvm/ui/RuntimeManagerPanel.java
- openwebstart/src/main/java/com/openwebstart/jvm/ui/RuntimeManagerPanelProvider.java
- openwebstart/src/main/java/com/openwebstart/launcher/OpenWebStartControlPanelStyle.java
- openwebstart/src/main/resources/META-INF/services/net.adoptopenjdk.icedteaweb.client.controlpanel.panels.provider.ControlPanelProvider
This PR is based on https://github.com/AdoptOpenJDK/IcedTea-Web/pull/448 and must not be merged before https://github.com/AdoptOpenJDK/IcedTea-Web/pull/448 is merged!
ITW JVM Panel is hidden
ITW About Panel is hidden
New OWS JVM Panel
> Control Center Panel Config

- openwebstart/pom.xml
This PR updates the install4j dependency to version 8
> Update to install4j 8

- openwebstart/src/main/java/com/openwebstart/jvm/RuntimeManagerConfig.java
- openwebstart/src/main/java/com/openwebstart/jvm/ui/RuntimeManagerPanel.java
- openwebstart/src/main/java/com/openwebstart/jvm/ui/RuntimeManagerPanelProvider.java
- openwebstart/src/main/java/com/openwebstart/jvm/ui/dialogs/ConfigurationDialog.java
- openwebstart/src/main/resources/i18n.properties
- openwebstart/src/main/resources/i18n_de.properties
- openwebstart/src/test/java/com/openwebstart/jvm/RemoteRuntimeManagerTest.java
- openwebstart/src/test/java/com/openwebstart/jvm/ui/sample/JvmManagerDemo.java
One usescase is not clear: 
what if the previously saved vendor name is not in the new vendor list fetched from the newly specified server url?
> Update Vendor list automatically

- openwebstart/src/main/java/com/openwebstart/launcher/ControlPanelLauncher.java
- openwebstart/src/main/java/com/openwebstart/launcher/PhaseTwoWebStartLauncher.java
@janakmulani can you please check if this changes helps you to start OWS from the IDE.
> Catching DLL Error

- openwebstart/src/main/java/com/openwebstart/about/OpenWebStartAboutPanel.java
- openwebstart/src/main/resources/com/openwebstart/about/about.template.html
The About dialog for OpenWebStart that is part of the control center.
This PR is based on https://github.com/karakun/OpenWebStart/pull/64 since I already started a basic about dialog in the mentioned PR. This PR should not be merged (reviewed) before https://github.com/karakun/OpenWebStart/pull/64 is merged.
> About dialog

- openwebstart/src/main/java/com/openwebstart/jvm/localfinder/MacRuntimeFinder.java
> OpenJDK that is installed by Homebrew can be found by JVM Manager

- openwebstart/src/main/java/com/openwebstart/launcher/OwsJvmLauncher.java
> add default JRE in case JNLP does not contain any

- openwebstart/src/main/java/com/openwebstart/app/ui/ApplicationManagerPanelProvider.java
> app pane removed

- INSTALL.md
This should be a starting point for documentation. It should also close #121
> Installation instructions file - ubuntu for start

- openwebstart/src/main/java/com/openwebstart/proxy/firefox/FirefoxProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/proxy/linux/LinuxProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/PacBasedProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/PacConstants.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/PacFileEvaluator.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/PacProxyCache.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/PacUtils.java
- openwebstart/src/main/resources/com/openwebstart/proxy/pac/pac-funcs.js
- openwebstart/src/test/java/com/openwebstart/proxy/pac/PacBasedProxyProviderTest.java
- openwebstart/src/test/java/com/openwebstart/proxy/pac/PacFileEvaluatorTest.java
- openwebstart/src/test/java/com/openwebstart/proxy/pac/PacUtilsTest.java
- openwebstart/src/test/resources/com/openwebstart/proxy/pac/simple-pac.js
Refactoring of PAC
Fixes for PAC
> UnitTests for PAC

- openwebstart/src/main/java/com/openwebstart/jvm/JavaRuntimeSelector.java
- openwebstart/src/main/java/com/openwebstart/jvm/LocalRuntimeManager.java
- openwebstart/src/main/java/com/openwebstart/jvm/ui/dialogs/DialogFactory.java
- openwebstart/src/main/java/com/openwebstart/launcher/JavaRuntimeProvider.java
- openwebstart/src/main/java/com/openwebstart/launcher/OwsJvmLauncher.java
- openwebstart/src/main/java/com/openwebstart/update/UpdatePanel.java
- openwebstart/src/main/resources/i18n.properties
- openwebstart/src/main/resources/i18n_de.properties
fixes #128
Better error handling /user notification when selecting runtime for jnlp file
> Better handling to receive runtime for given JNLP file

- openwebstart/src/main/java/com/openwebstart/proxy/windows/WindowsProxyProvider.java
Looks like activating PAC on windows does not set "ProxyEnable" to true.
> PAC does not depend on "ProxyEnable" value

- openwebstart/src/main/java/com/openwebstart/jvm/util/JavaRuntimePropertiesDetector.java
- openwebstart/src/main/java/com/openwebstart/os/linux/LinuxEntryFactory.java
- openwebstart/src/main/java/com/openwebstart/os/mac/icns/IcnsFactory.java
- openwebstart/src/main/java/com/openwebstart/proxy/linux/GnomeProxyConfigReader.java
- openwebstart/src/main/java/com/openwebstart/proxy/windows/RegistryQuery.java
- openwebstart/src/main/java/com/openwebstart/proxy/windows/WindowsProxy.java
- openwebstart/src/main/java/com/openwebstart/util/ProcessResult.java
- openwebstart/src/main/java/com/openwebstart/util/ProcessUtil.java
Better process execution:
- do not wait endless
- util method
- error handling
> Process execution

- openwebstart/src/main/java/com/openwebstart/config/OwsDefaultsProvider.java
- openwebstart/src/main/java/com/openwebstart/launcher/OpenWebStartLauncher.java
- openwebstart/src/main/java/com/openwebstart/proxy/ProxyProviderType.java
- openwebstart/src/main/java/com/openwebstart/proxy/firefox/FirefoxProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/proxy/linux/LinuxProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/proxy/mac/MacProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/proxy/manual/ManualPacFileProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/DefaultPacProxyCache.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/NoopPacProxyCache.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/PacBasedProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/PacFileEvaluator.java
- openwebstart/src/main/java/com/openwebstart/proxy/pac/PacProxyCache.java
- openwebstart/src/main/java/com/openwebstart/proxy/windows/WindowsProxyProvider.java
- openwebstart/src/main/java/com/openwebstart/ui/ErrorDialog.java
- openwebstart/src/test/java/com/openwebstart/proxy/pac/PacBasedProxyProviderTest.java
- openwebstart/src/test/java/com/openwebstart/proxy/pac/PacFileEvaluatorTest.java
+ Cache of PAC can be disabled
> PAC can handle URI 

- openwebstart/src/main/java/com/openwebstart/proxy/config/ConfigBasedProvider.java
> switch to IpUtil for localhost lookup

- openwebstart/src/main/java/com/openwebstart/jvm/localfinder/JdkFinder.java
- openwebstart/src/main/java/com/openwebstart/util/ExtractUtil.java
- openwebstart/src/test/java/com/openwebstart/util/ExtractUtilTest.java
> unwrap extracted folders

- openwebstart/src/main/java/com/openwebstart/jvm/localfinder/JdkFinder.java
- openwebstart/src/main/java/com/openwebstart/jvm/os/OperationSystem.java
Reported in the forum: https://board.karakun.com/viewtopic.php?f=21&t=76&p=233#p233
> show arch of local JRE instead of local OS

- openwebstart/src/main/java/com/openwebstart/controlpanel/FormPanel.java
- openwebstart/src/main/java/com/openwebstart/controlpanel/MaximumLayoutManager.java
- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadDetailListModel.java
- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadDetailListRenderer.java
- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadDialog.java
- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadIndicator.java
- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadResourceState.java
- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadState.java
- openwebstart/src/main/java/com/openwebstart/extensionpoint/OwsExtensionPoint.java
- openwebstart/src/main/java/com/openwebstart/launcher/ControlPanelLauncher.java
- openwebstart/src/main/java/com/openwebstart/launcher/PhaseTwoWebStartLauncher.java
- openwebstart/src/main/java/com/openwebstart/ui/DialogWithDetails.java
- openwebstart/src/main/java/com/openwebstart/ui/ErrorDialog.java
- openwebstart/src/main/resources/i18n.properties
- openwebstart/src/test/java/com/openwebstart/download/ApplicationDownloadIndicatorSample.java
- openwebstart/src/test/java/com/openwebstart/downloadcount/UpdateCount.java
Copy of https://github.com/karakun/OpenWebStart/pull/286 that I closed based on a bug in GitHub (new commits have not been shown in PR). Needs https://github.com/AdoptOpenJDK/IcedTea-Web/pull/675 to be merged.
> Custom download indicator

- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadDialog.java
- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadIndicator.java
Based on https://github.com/AdoptOpenJDK/IcedTea-Web/pull/682
> download-indicator-update

- openwebstart/src/main/java/com/openwebstart/launcher/InitialConfigurationCheck.java
> add missing keys for unattended configuration

- openwebstart/src/test/java/com/openwebstart/jvm/json/JsonHandlerTest.java
- openwebstart/src/test/java/com/openwebstart/jvm/json/Person.java
- openwebstart/src/test/java/com/openwebstart/jvm/json/PersonModel.java
Added Tests for JsonHandler class
> Tests for JsonHandler

- documentation/faq/FAQ.adoc
- documentation/guide/OWSGuide.adoc
- documentation/pom.xml
- openwebstart/pom.xml
- pom.xml
- generate PDF and HTML version of guide and FAQ
-> upload to openwebstart.com web site already prepared on team city side
-> once this is on master we can remove handcrafted PDFs and update the links in the OWS forum
> make documentation a maven module to generate asciidoc

- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadDialog.java
- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadIndicator.java
- openwebstart/src/main/java/com/openwebstart/extensionpoint/OwsExtensionPoint.java
- openwebstart/src/main/java/com/openwebstart/launcher/ControlPanelLauncher.java
- openwebstart/src/main/java/com/openwebstart/launcher/PhaseTwoWebStartLauncher.java
- openwebstart/src/test/java/com/openwebstart/download/ApplicationDownloadIndicatorSample.java
> Focus of download indicator

- openwebstart/src/main/java/com/openwebstart/config/OwsDefaultsProvider.java
> fix warning about unknown property

- openwebstart/src/main/java/com/openwebstart/download/ApplicationDownloadIndicator.java
> close dialog in ui thread

- documentation/guide/OWSGuide.adoc
- openwebstart/src/main/java/com/openwebstart/config/OwsDefaultsProvider.java
- openwebstart/src/main/java/com/openwebstart/jvm/ui/dialogs/ConfigurationDialog.java
- ALLOW_VENDOR_FROM_JNLP is true and disabled when Any Vendor selected
- update OWS guide
> OWS-534: Improve any vendor settings behaviour

- openwebstart/src/test/java/com/openwebstart/jvm/RemoteRuntimeManagerTest.java
Fix unit test after removal of adopt JVMs from jvms.json.
> Fix unit test after removal of adopt JVMs from jvms.json.

- openwebstart/src/main/java/com/openwebstart/logging/LoggingPanel.java
- openwebstart/src/main/resources/i18n.properties
- openwebstart/src/main/resources/i18n_de.properties
Add the possibility to log the JNLP file content
> Log jnlp content

- openwebstart/src/main/java/com/openwebstart/install4j/Install4JUpdateHandler.java
- openwebstart/src/main/java/com/openwebstart/launcher/ControlPanelLauncher.java
- openwebstart/src/main/java/com/openwebstart/launcher/PhaseTwoWebStartLauncher.java
Needs to be tested on OS like Linux and Mac
> proxy auth during update

- openwebstart/src/main/java/com/openwebstart/launcher/OwsJvmLauncher.java
> Jnlp specific vmargs
